### ISSUE TITLE
Service Unavailable

### ISSUE THREAD

**Issue by romani** [sevntu-checkstyle/methods-distance#61]
https://methods-distance.herokuapp.com/dsm?source_url=https://raw.githubusercontent.com/checkstyle/checkstyle/671d4e5c1b57d6457df94cc02af339c9db2d30e1/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/SummaryJavadocCheck.java

```
HTTP ERROR: 503

Problem accessing /dsm. Reason:

    Service Unavailable

Powered by Jetty:// 9.3.8.v20160314
```

**Comment by romani** [comment]
>Thank you for reaching out to heroku-opensource-credits@s....forc...com in reference to requesting Heroku Credits for qualified and selected Open Source Programs.
Applications will be reviewed on a monthly basis, starting in February 2023. Once your application has been reviewed you will receive a notification regarding the application status, denoting if the credits have been approved or denied.
In the meantime, should you have any questions or feedback, please
do not hesitate to contact us via the above email address.
--
The Heroku Open Source Credits team`

**Comment by romani** [comment]
I got response from support.
I applied to free tier at https://www.heroku.com/open-source-credit-program

**Comment by romani** [comment]
I we be not accepted we can try https://railway.app/ , it has some free basic credit for each month that will be enough for our application, that has almost no traffic.

**Comment by romani** [comment]
we are approved for Free plan on Heroku, I will do deploy as credits are applied to plan.

**Comment by romani** [comment]
```
2023-06-01T13:14:24.214896+00:00 heroku[web.1]: Restarting
2023-06-01T13:14:24.237980+00:00 heroku[web.1]: State changed from up to starting
2023-06-01T13:14:24.768891+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2023-06-01T13:14:24.804734+00:00 app[web.1]: 2023-06-01 13:14:24.804:INFO:oejs.ServerConnector:Thread-0: Stopped ServerConnector@61832929{HTTP/1.1,[http/1.1]}{0.0.0.0:37416}
2023-06-01T13:14:24.806319+00:00 app[web.1]: 2023-06-01 13:14:24.806:INFO:oejsh.ContextHandler:Thread-0: Stopped o.e.j.w.WebAppContext@21588809{/,null,UNAVAILABLE}{file:///app/methods-distance-web/target/app.war}
2023-06-01T13:14:24.807489+00:00 app[web.1]: 2023-06-01 13:14:24.807:WARN:oejs.ServletContextHandler:Thread-0: ServletContextHandler.setHandler should not be called directly. Use insertHandler or setSessionHandler etc.
2023-06-01T13:14:24.985296+00:00 heroku[web.1]: Process exited with status 143
2023-06-01T13:14:27.452200+00:00 heroku[web.1]: Starting process with command `java $JAVA_OPTS -jar methods-distance-web/target/dependency/jetty-runner.jar --port 5343 methods-distance-web/target/app.war`
2023-06-01T13:14:28.052386+00:00 app[web.1]: Setting JAVA_TOOL_OPTIONS defaults based on dyno size. Custom settings will override them.
2023-06-01T13:14:28.055570+00:00 app[web.1]: Picked up JAVA_TOOL_OPTIONS: -Xmx300m -Xss512k -XX:CICompilerCount=2 -Dfile.encoding=UTF-8 
2023-06-01T13:14:28.145191+00:00 app[web.1]: 2023-06-01 13:14:28.144:INFO::main: Logging initialized @85ms
2023-06-01T13:14:28.150672+00:00 app[web.1]: 2023-06-01 13:14:28.150:INFO:oejr.Runner:main: Runner
2023-06-01T13:14:28.227440+00:00 app[web.1]: 2023-06-01 13:14:28.227:INFO:oejs.Server:main: jetty-9.3.8.v20160314
2023-06-01T13:14:29.550371+00:00 heroku[web.1]: State changed from starting to up
2023-06-01T13:14:29.390318+00:00 app[web.1]: 2023-06-01 13:14:29.389:WARN:oejw.WebAppContext:main: Failed startup of context o.e.j.w.WebAppContext@21588809{/,file:///tmp/jetty-0.0.0.0-5343-app.war-_-any-1577038241484362534.dir/webapp/,UNAVAILABLE}{file:///app/methods-distance-web/target/app.war}
2023-06-01T13:14:29.390337+00:00 app[web.1]: java.lang.RuntimeException: Error scanning entry META-INF/versions/9/module-info.class from jar file:///tmp/jetty-0.0.0.0-5343-app.war-_-any-1577038241484362534.dir/webapp/WEB-INF/lib/picocli-4.6.1.jar
2023-06-01T13:14:29.390338+00:00 app[web.1]: 	at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:937)
2023-06-01T13:14:29.390339+00:00 app[web.1]: 	at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:851)
2023-06-01T13:14:29.390340+00:00 app[web.1]: 	at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:163)
2023-06-01T13:14:29.390340+00:00 app[web.1]: 	at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:548)
2023-06-01T13:14:29.390340+00:00 app[web.1]: 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
2023-06-01T13:14:29.390341+00:00 app[web.1]: 	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
2023-06-01T13:14:29.390342+00:00 app[web.1]: 	at java.lang.Thread.run(Thread.java:750)
2023-06-01T13:14:29.390343+00:00 app[web.1]: Caused by: 
2023-06-01T13:14:29.390344+00:00 app[web.1]: java.lang.IllegalArgumentException
2023-06-01T13:14:29.390344+00:00 app[web.1]: 	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
2023-06-01T13:14:29.390345+00:00 app[web.1]: 	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
2023-06-01T13:14:29.390345+00:00 app[web.1]: 	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
2023-06-01T13:14:29.390345+00:00 app[web.1]: 	at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:1003)
2023-06-01T13:14:29.390346+00:00 app[web.1]: 	at org.eclipse.jetty.annotations.AnnotationParser.parseJarEntry(AnnotationParser.java:984)
2023-06-01T13:14:29.390346+00:00 app[web.1]: 	at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:933)
2023-06-01T13:14:29.390346+00:00 app[web.1]: 	at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:851)
2023-06-01T13:14:29.390346+00:00 app[web.1]: 	at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:163)
2023-06-01T13:14:29.390347+00:00 app[web.1]: 	at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:548)
2023-06-01T13:14:29.390347+00:00 app[web.1]: 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
2023-06-01T13:14:29.390347+00:00 app[web.1]: 	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
2023-06-01T13:14:29.390350+00:00 app[web.1]: 	at java.lang.Thread.run(Thread.java:750)
2023-06-01T13:14:29.401018+00:00 app[web.1]: 2023-06-01 13:14:29.400:INFO:oejs.ServerConnector:main: Started ServerConnector@61832929{HTTP/1.1,[http/1.1]}{0.0.0.0:5343}
2023-06-01T13:14:29.401130+00:00 app[web.1]: 2023-06-01 13:14:29.401:INFO:oejs.Server:main: Started @1345ms
2023-06-01T13:15:06.318390+00:00 heroku[router]: at=info method=GET path="/" host=methods-distance.herokuapp.com request_id=da3cfb65-72ad-4b1c-a5db-5bc1a3097e15 fwd="76.103.49.161" dyno=web.1 connect=0ms service=5ms status=503 bytes=565 protocol=https
2023-06-01T13:15:53.076912+00:00 heroku[router]: at=info method=GET path="/dsm?source_url=https://raw.githubusercontent.com/checkstyle/checkstyle/b4e884c2ff3bef182b045692b59c1aceae3cb892/src/main/java/com/puppycrawl/tools/checkstyle/Checker.java" host=methods-distance.herokuapp.com request_id=0ea40481-a095-43fa-87d7-99d790f1524b fwd="76.103.49.161" dyno=web.1 connect=0ms service=1ms status=503 bytes=568 protocol=https
```
